### ISSUE TITLE
problem extracting text on a two columns layout

### ISSUE THREAD

**Issue by manentai** [sambitdash/PDFIO.jl#112]
I have opened a question here: https://discourse.julialang.org/t/how-to-extract-data-from-pdf-with-two-columns/108008
but maybe this is the right place... 

from this slide

![](https://global.discourse-cdn.com/julialang/original/3X/9/7/97498f3522bfb241217c41e32fcbd694695c1554.png)

using this:
```
doc = pdDocOpen(src)
docinfo = pdDocGetInfo(doc)
npage = pdDocGetPageCount(doc)
io = IOBuffer()
for i = 1:npage
    page = pdDocGetPage(doc, i)
    pdPageExtractText(io, page)
end
pdDocClose(doc)
```

I get this:
`gives a poor performance:
● SAM: The solution ○ EU incubators / accelerators: ~1200 market size ○ EU VC: ~500 ● SOM: ○ IT incubators / ● TAM:○ 1.35M tech startups accelerators: ~250, worldwide ○ IT VCs: ~60 ○ ~7000 incubators / accelerators worldwide, ○ proxies to enter and counting 5000 startups ○ ~2500 VC ﬁrms, half of them on growth giano.rocks`

which is kind of ignoring the two columns layout. I am trying to understand from the API if there's a way to simply extract all the objects in the page and then extract texts from these objects.
What am I missing?

**Comment by manentai** [comment]
thanks for the pointers, since `pdPageEvalContent` from #17 does not seem to exist anymore, is `pdPageGetContentObjects` the right one to get the structure now?

**Comment by sambitdash** [comment]
https://github.com/sambitdash/PDFIO.jl/blob/826552f6460513b15e15b15b2505bb2e400117ed/src/PDPage.jl#L11 is exported and is very much available.

**Comment by manentai** [comment]
sorry, I cannot find it here: https://docs.juliahub.com/PDFIO/cmOJE/0.1.14/, and when I try to use it I get `UndefVarError: `pdPageEvalContent` not defined

Stacktrace:
 [1] top-level scope
   @ [/mnt/data/projects/GenieGiano/test.ipynb:10](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a224d4f4c4c595f6761626279227d.vscode-resource.vscode-cdn.net/mnt/data/projects/GenieGiano/test.ipynb:10)`

**Comment by manentai** [comment]
> https://github.com/sambitdash/PDFIO.jl/blob/826552f6460513b15e15b15b2505bb2e400117ed/src/PDPage.jl#L11
> 
> is exported and is very much available. However, this method is a callback and depends on the PDF page object type. It is not documented and can only be used by someone who understands PDF specifications well enough to work with the callback.

ok fair enough I guess...

**Comment by sambitdash** [comment]
```
function pdPageExtractText(io::IO, page::PDPage)
    state = pdPageEvalContent(page)
    show_text_layout!(io, state)
    return io
end
```
`pdPageExtractText` calls `pdPageEvalContent` that populates the content objects in the `state` object. `show_text_layout!` does the actual layout translation. It has no understanding of multi-column text. It just tries to map the text from left to right and top to bottom. PDF as a format does not understand columns. However, you can take the content objects and render the text objects using your heuristics. That is the suggestion given in #17.
