### ISSUE TITLE
Unable to read in PDF

### ISSUE THREAD

**Issue by jacobcvt12** [sambitdash/PDFIO.jl#18]
I am attempting to read in [this pdf](https://github.com/sambitdash/PDFIO.jl/files/1661854/16-969_o7jp.pdf). Unfortunately, the code seems stuck on the first page. Any thoughts on why this is? I was able to run this code on another PDFs.

```julia
using PDFIO

fname = "16-969_o7jp.pdf"
doc = pdDocOpen(fname)

open("tmp.txt", "w") do io
    page = pdDocGetPage(doc, 1)
    pdPageExtractText(io, page)
end

pdDocClose(doc)
```

I've also tried on other pages of the PDF and see similar results - Julia works (indefinitely), but I see no error messages, and nothing is printed to the file.

**Comment by sambitdash** [comment]
The file has an unusual PS definition in the CMap file:

```
/CIDSystemInfo <<
                   /Registry (PBPLFD+Courier+0) def
                   /Ordering (T1UV) def
                   /Supplement 0 def
>>
```
In this format of CMaps typically the `def` keyword is not used. 

```
/CIDSystemInfo <<
       /Registry (F15+0) 
       /Ordering (T1UV) 
      /Supplement 0 >> def
```
The `parse_dict` can be made more tolerant. But I think the CMaps in these files are essentially corrupt.

**Comment by sambitdash** [comment]
Closing as now fixed.

**Comment by sambitdash** [comment]
@jacobcvt12 As you can see I have checked-in the changes and tested in the local system. However, I did not check-in test case as I don't own the file to share. Since, you own the file and if you think you can contribute to the test cases feel free to right a test case and upload the file to the test files collection so that this issue can be tracked during every build. 

Thank you again for your submission and using PDFIO.

**Comment by jacobcvt12** [comment]
Thanks for this update. With regard to the file, it is a transcription of a oral arguments in the supreme court of the united states (accessible [here](https://www.supremecourt.gov/oral_arguments/argument_transcript/2017)). I don't own this file, but I imagine that using it in a unit test classifies as fair use. I'll work on a unit test and contribute in the near future.

**Comment by sambitdash** [comment]
Thanks for your help @jacobcvt12. Will look forwards to it.

**Comment by sambitdash** [comment]
Test case added with https://github.com/sambitdash/PDFIO.jl/commit/fc3e92c6604310546d44d7dd8db93cbbd3171d7d
