### ISSUE TITLE
CDDate(test) == CDDate(test) returns false

### ISSUE THREAD

**Issue by gwierzchowski** [sambitdash/PDFIO.jl#30]
Working on unit test for PR #26 I noticed following unexpected behavior:
```
(v1.0) julia> test = "D:20090807192622";

(v1.0) julia> CDDate(test) == CDDate(test)
false
```
Looking at code I see 2 following problems:
1) reg ex for date:
```julia
r"D\s*:\s*(?<dt>\d{12})\s*(?<ut>[+-Z])\s*((?<tzh>\d{2})'\s*(?<tzm>\d{2}))?"
```
do not strictly conforms Adobe PDF date spec.
More correct would be:
```julia
r"D\s*:\s*(?<YYYY>\d{4})(?<MM>\d{2})?(?<DD>\d{2})?(?<HH>\d{2})?(?<mm>\d{2})?(?<SS>\d{2})?\s*((?<ut>[-+Z])\s*(?<tzh>\d{2}))?(\s*'\s*(?<tzm>\d{2}))?\s*"
```
2) == for CDDate fallback into identity, I would like to implement:
```julia
(==)(x::T, y::T) where {T<: CDDate} 
```

I'm working on fix, let me know if you welcome PR, and if better to do separate PR or altogether with corrected PR #26 ?
Thanks, Best Regards, GW

**Comment by sambitdash** [comment]
I think as per PDF spec the whitespaces are not expected in the regexp. So they can be removed. Moreover, you will need to implement the `isless` and `isequal` operator for date objects have trichotomy property.

**Comment by sambitdash** [comment]
Ideally, we should make separate PRs for each issue.

**Comment by sambitdash** [comment]
You may not need anything like: 
```
(==)(x::T, y::T) where {T<: CDDate} 
```
The below should suffice.
```
isless(x::CDDate, y::CDDate)
isequal(x::CDDate, y::CDDate)
```
I do not think anyone will like to derive from `CDDate`. `CDDate` are kind of final types in that sense.

**Comment by gwierzchowski** [comment]
In julia 1.0 it is little strange:
```julia
<(x, y) = isless(x, y)
```
but:
```julia
isequal(x, y) = x == y
#....
==(x, y) = x === y
```
So I implemented `==` and `isless` ;/
I agree, no need for `T<:CDDate`

**Comment by sambitdash** [comment]
> do not strictly conforms Adobe PDF date spec.
> More correct would be:
> 
> ```julia
> r"D\s*:\s*(?<YYYY>\d{4})(?<MM>\d{2})?(?<DD>\d{2})?(?<HH>\d{2})?(?<mm>\d{2})?(?<SS>\d{2})?\s*((?<ut>[-+Z])\s*(?<tzh>\d{2}))?(\s*'\s*(?<tzm>\d{2}))?\s*"
> ```

Wonder alternate to try: 

`r"D:(?<dt>(\d\d){2,6})(?<tz>((?<ahead>[+-])(?<tzh>\d\d)('(?<tzm>\d\d))?|Z))?"`
