### ISSUE TITLE
Extracting boxes

### ISSUE THREAD

**Issue by kskyten** [sambitdash/PDFIO.jl#57]
I have a pdf with important points drawn in boxes using path commands. For example:
```
Q
538.02 6098.07 3316.68 4.14063 re
f
538.02 5395.17 4.14063 705.059 re
f
3850.56 5395.17 4.14063 705.059 re
f
538.02 5393.19 3316.68 4.13672 re
f
q
```
How can I extract these?

**Comment by sambitdash** [comment]
PDFIO does not support graphics extraction currently. However, you can use the techniques suggested in #55 to extract objects you desire.

**Comment by kskyten** [comment]
Thanks for the help. Turns out I need all of them together (i.e between `Q` and `q`), so it was easier to just filter them out from a page instead of overloading `evalContent!`. This is a bit hacky and probably pretty specific to the pdf I'm processing, but it works for me.
