### ISSUE TITLE
Not able to execute any functions on a basic PDF. Error: Found ' (32)' Expected '<' here

### ISSUE THREAD

**Issue by tuckertranslator** [sambitdash/PDFIO.jl#72]
Hi there.
I am getting an error when I try to execute getPDFText() or pdDocOpen() or any other function. This the error: 
_Found ' (32)' Expected '<' here_

And here is the first few lines of stack trace:
the stacktrace:
 _[1] error(::String) at ./error.jl:33
 [2] skipv at /Users/tuckercahillchambers/.julia/packages/PDFIO/Miu63/src/BufferParser.jl:25 [inlined]
 [3] read_trailer(::IOStream, ::Int64) at /Users/tuckercahillchambers/.julia/packages/PDFIO/Miu63/src/CosDoc.jl:382_

I have searched for this error and come up with nothing. Any ideas on where to go from here?
Thank you.

**Comment by sambitdash** [comment]
@tuckertranslator, can you share the file where you faced the error? If you can share the file here in public, you can send the file to me by e-mail. Without the file it'll be hard for me to to comment on the issue.

**Comment by sambitdash** [comment]
You can also run the default tests on the PDFIO installation by using the following commands:

```
(PDFIO) pkg> test PDFIO
   Testing PDFIO
 Resolving package versions...
Copying Arial.afm to /home/sambit/.julia/dev/PDFIO/test/../data/fonts
┌ Warning: Embedded file streams without Crypt filters may not decrypt
└ @ PDFIO.Cos ~/.julia/dev/PDFIO/src/StdSecHandler.jl:357
┌ Warning: Embedded file streams without Crypt filters may not decrypt
└ @ PDFIO.Cos ~/.julia/dev/PDFIO/src/PKISecHandler.jl:62
Test Summary: | Pass  Total
PDFIO tests   |  120    120
Removing Arial.afm from /home/sambit/.julia/dev/PDFIO/test/../data/fonts
   Testing PDFIO tests passed 
```
If the test passes the error must be due to something specific in the PDF file.

**Comment by tuckertranslator** [comment]
Hi Sambit. I emailed you the PDF as it is a bit sensitive. I ran the package test per your suggestion, and the package seems to be fine. I will update here later on, if we manage to resolve the PDF issue. 
Thank you.

**Comment by sambitdash** [comment]
Fixed in: https://github.com/sambitdash/PDFIO.jl/commit/89364fbcf46cc718e5eef1643da7ec0602795eba

**Comment by sambitdash** [comment]
Closing.
