### ISSUE TITLE
ASCIIHexDecode should be vectorized

### ISSUE THREAD

**Issue by sambitdash** [sambitdash/PDFIO.jl#8]
The conversion is relatively simple. Hence, should be made a vector operation and not byte by byte read.

**Comment by wstaelens** [comment]
@sambitdash can you explain more how you can "vectorize" this to make it a vector operation?

**Comment by sambitdash** [comment]
The vector operation code generation is to be carried out by the compiler not human optimized as the code needs to be run on varied disparate processors. Most processors support vector operations like SIMD if the code does not have unnecessary branching. However, if you are look at the byte operation code it's full of branching. A sample code for this can be seen in the comment:

https://github.com/JuliaLang/julia/pull/23267#issuecomment-323522350

However, the generated code was not reviewed for potential further optimizations. Hope this explains what is needed.

**Comment by sambitdash** [comment]
This may not be needed as PDF spec does not mandate the streams to have even number of hexits. It can also have control characters like CR-LF. So the branching may be significantly higher. Closing now.

**Comment by sambitdash** [comment]
Current implementation is about 60ms for a 10Mb stream.
