### ISSUE TITLE
Getting assertation error in show_text_layout!

### ISSUE THREAD

**Issue by sebastianpech** [sambitdash/PDFIO.jl#81]
I have a pdf which fails at this
https://github.com/sambitdash/PDFIO.jl/blob/eeff74cd01dd29839465bb070b63c929bacd5e16/src/PDPageElement.jl#L618
assertation.

[fails.pdf](https://github.com/sambitdash/PDFIO.jl/files/3907094/fails.pdf)

**Comment by sebastianpech** [comment]
This happens when extracting the pdfs text

**Comment by sambitdash** [comment]
Extremely small characters affect the formatting so they must be ignored. The assertion was introduced to keep a check on them. In this case a textrun as 0x200b which is zero width space character of unicode leading to assertion failure. The textruns have to be ignored rather than asserted on.

**Comment by sambitdash** [comment]
https://github.com/sambitdash/PDFIO.jl/commit/759200f14f637eb87e3bec5e49de0695009c7504 should fix this issue.

**Comment by sebastianpech** [comment]
Works! Thanks for your effort. I have more to come will open an issue later
