### ISSUE TITLE
How to retrieve text from pdPageExtractText(stdout, page)?

### ISSUE THREAD

**Issue by flalom** [sambitdash/PDFIO.jl#82]
I am new in Julia and I am very interested in PDFIO.jl.
I am trying to save the text output from the pdPageExtractText(stdout, page) in the text variable but I can't because I get this object:
IJulia.IJuliaStdio{Base.PipeEndpoint} IOContext(Base.PipeEndpoint(Base.Libc.WindowsRawSocket(0x0000000000000384) open, 0 bytes waiting))).

Thank you for your help!
Can I contribute?

**Comment by sambitdash** [comment]
String(take!(pdPageExtractText(IOBuffer(), page)))) should work.
