### ISSUE TITLE
Would you give additional examples of how to work with pages?

### ISSUE THREAD

**Issue by ValeriiBaidin** [sambitdash/PDFIO.jl#86]
Would you give additional examples of how to work with pages and show all the advantages. Right now it's very confusing. 
Thank you in advance.

**Comment by sambitdash** [comment]
@vbaidin can you clarify what you will need to do with pages? You may also need to understand PDF specification to understand the page objects that you want to access and use.

**Comment by vbaidin** [comment]
> @vbaidin can you clarify what you will need to do with pages? You may also need to understand PDF specification to understand the page objects that you want to access and use.

All kids of example. Even how to convert any page to string. How to use page objects. 
It should be easy for any undergraduate freshman.

**Comment by sambitdash** [comment]
@vbaidin  can you describe what you are trying to do? PDF specification has a wide variety of objects classified as page objects.

**Comment by sambitdash** [comment]
Open ended requirement, hence closing.
