### ISSUE TITLE
ERROR: MethodError: no method matching String(::PDFIO.Cos.CosIndirectObject{CosName})

### ISSUE THREAD

**Issue by EddieCueto** [sambitdash/PDFIO.jl#92]
I get this error while using pdPageExtractText on this pdf on page 6 only which is a bit strange
[Neural Ordinary Differential Equations.pdf](https://github.com/sambitdash/PDFIO.jl/files/4978114/Neural.Ordinary.Differential.Equations.pdf)

**Comment by sambitdash** [comment]
Fixed https://github.com/sambitdash/PDFIO.jl/commit/b9163b04d5c995c044991867555cb424346c4dbf
