### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DilumAluthge** [sambitdash/PDFIO.jl#93]
The latest registered release (v0.1.10) cannot be `import`ed on the latest Julia nightly.

However, the master branch `PDFIO#master` is able to be `import`ed on Julia nightly.

Therefore, could we get a new release of PDFIO?

**Comment by sambitdash** [comment]
Packages are not kept aligned to nightly ever. They are only built once a stable version is released. If the version in the nightly built requires another version of Julia then a new version shall be released. Hence, closing this as we do not normally keep compliance with the nightly version of Julia.

**Comment by sambitdash** [comment]
tag v0.1.11 should address the nightly build issue.
