### ISSUE TITLE
Support for AbstractTrees v0.3

### ISSUE THREAD

**Issue by Nosferican** [sambitdash/PDFIO.jl#98]
The test for `Outlines` fails with AbstractTrees v0.3 fixing it at v0.2. This makes it that other packages that rely on the dependency like DataFrames.jl are held back at v0 preventing it from using v1 in the same environment. Would be nice if the issue can be fixed such that the deps can allow for AbstractTrees v0.3. Thanks!

PS: BinDeps v1 seems to be working with the package w/no issues.

**Comment by sambitdash** [comment]
@Nosferican feel free to send a PR if you have a solution that can address the issue.

**Comment by Nosferican** [comment]
I tried to see if it was something trivial but couldn't tell how exactly how AbstractTrees was impacting the test case.

**Comment by sambitdash** [comment]
Fixed in: https://github.com/sambitdash/PDFIO.jl/commit/64628309fea6e8f00834072a1ebd25760b8952f6
